/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type AudioMode = "silent" | "listening" | "thinking" | "speaking";
export type AudioResourceId = string | null;
export type Cancellable = boolean;
export type CorrelationId = string;
export type DurationMs = number;
export type IntentId = string;
export type Brightness = number;
export type OffsetMs = number;
/**
 * @minItems 3
 * @maxItems 3
 */
export type Rgb = [unknown, unknown, unknown];
export type LightTrack = LightKeyframe[];
export type Channel = string;
export type Easing = string;
export type OffsetMs1 = number;
export type Value = number;
export type Keyframes = MotionKeyframe[];
export type MotionTracks = MotionTrack[];
export type Priority = number;
export type TimelineId = string;
export type Component = string;
export type Detail = string | null;
export type Status = string;
export type Alternatives = string[];
export type AnchorName = string | null;
export type CanonicalLabel = string | null;
export type DepthBand = string | null;
export type EvidenceIds = string[];
export type HorizontalRegion = string | null;
export type ObservedAtUtc = string | null;
export type Status1 = string;
export type AnchorName1 = string | null;
export type Confidence = number;
export type DepthBand1 = string | null;
export type HorizontalRegion1 = string | null;
export type Label = string;
export type TrackId = string;
export type CapturedAtMonoNs = number;
export type Confidence1 = number;
export type CorrelationId1 = string;
export type EmittedAtMonoNs = number;
export type EventId = string;
export type FrameRef = string | null;
export type Kind = string;
export type SchemaVersion = string;
export type SessionId = string;
export type ObservationSource = "capture" | "face" | "gaze" | "audio" | "object" | "enrichment" | "operator" | "system";
export type WallTimeUtc = string;
export type EngagementConfidence = number;
export type EngagementScore = number;
export type IsActiveSpeaker = boolean;
export type PersonId = string;
export type SocialState = "idle" | "candidate" | "engaged" | "disengaged" | "seeking_attention";
export type AsOfMonoNs = number;
export type Health = ComponentHealth[];
export type Objects = ObjectState[];
export type People = PersonState[];
export type PrimaryPersonId = string | null;
export type Revision = number;
export type SchemaVersion1 = string;
export type SessionId1 = string;
export type SnapshotId = string;

export interface SocialLampContracts {
  AudioMode?: AudioMode;
  BehaviorTimeline?: BehaviorTimeline;
  ComponentHealth?: ComponentHealth;
  LightKeyframe?: LightKeyframe;
  MemoryResult?: MemoryResult;
  MotionKeyframe?: MotionKeyframe;
  MotionTrack?: MotionTrack;
  ObjectState?: ObjectState;
  ObservationEvent?: ObservationEvent;
  ObservationSource?: ObservationSource;
  PersonState?: PersonState;
  SocialState?: SocialState;
  WorldSnapshot?: WorldSnapshot;
  [k: string]: unknown;
}
export interface BehaviorTimeline {
  audio_resource_id?: AudioResourceId;
  cancellable: Cancellable;
  correlation_id: CorrelationId;
  duration_ms: DurationMs;
  intent_id: IntentId;
  light_track?: LightTrack;
  motion_tracks: MotionTracks;
  priority: Priority;
  timeline_id: TimelineId;
}
export interface LightKeyframe {
  brightness: Brightness;
  offset_ms: OffsetMs;
  rgb: Rgb;
}
export interface MotionTrack {
  channel: Channel;
  keyframes: Keyframes;
}
export interface MotionKeyframe {
  easing?: Easing;
  offset_ms: OffsetMs1;
  value: Value;
}
export interface ComponentHealth {
  component: Component;
  detail?: Detail;
  status: Status;
}
export interface MemoryResult {
  alternatives?: Alternatives;
  anchor_name?: AnchorName;
  canonical_label?: CanonicalLabel;
  depth_band?: DepthBand;
  evidence_ids?: EvidenceIds;
  horizontal_region?: HorizontalRegion;
  observed_at_utc?: ObservedAtUtc;
  status: Status1;
}
export interface ObjectState {
  anchor_name?: AnchorName1;
  confidence: Confidence;
  depth_band?: DepthBand1;
  horizontal_region?: HorizontalRegion1;
  label: Label;
  track_id: TrackId;
}
export interface ObservationEvent {
  captured_at_mono_ns: CapturedAtMonoNs;
  confidence: Confidence1;
  correlation_id: CorrelationId1;
  emitted_at_mono_ns: EmittedAtMonoNs;
  event_id: EventId;
  frame_ref?: FrameRef;
  kind: Kind;
  payload: Payload;
  schema_version?: SchemaVersion;
  session_id: SessionId;
  source: ObservationSource;
  wall_time_utc: WallTimeUtc;
}
export interface Payload {
  [k: string]: unknown;
}
export interface PersonState {
  engagement_confidence: EngagementConfidence;
  engagement_score: EngagementScore;
  is_active_speaker?: IsActiveSpeaker;
  person_id: PersonId;
}
export interface EngagementCalibrationSnapshot {
  failure_reason?: string | null;
  mode: string;
  person_id?: string | null;
  progress: number;
  quality: string;
  sample_count: number;
  state: string;
}
export interface WorldSnapshot {
  as_of_mono_ns: AsOfMonoNs;
  audio_mode: AudioMode;
  engagement_calibration: EngagementCalibrationSnapshot;
  health: Health;
  objects: Objects;
  people: People;
  primary_person_id: PrimaryPersonId;
  revision: Revision;
  schema_version?: SchemaVersion1;
  session_id: SessionId1;
  snapshot_id: SnapshotId;
  social_state: SocialState;
}
